name: first-workflow
on: workflow_dispatch
jobs: 
  first_job: 
    runs-on: ubuntu-slim
    steps: 
      - name: Greetings
        run: echo "Hello World!"
      - name: Sayonara
        run: echo "Bye, Bye!"
